language: php

php:
  - 8.2.9

before_install:
  - sudo apt-cache search libonig

install:
  - sudo apt-get update
  - sudo apt-get install -y libonig-dev
  - composer install --no-interaction

script:
  - cd firefly-iii-asg
  - vendor/bin/phpunit --configuration phpunit.xml

branches:
  only:
    - 4.3-dev

cache:
  directories:
    - vendor
    - $HOME/.composer/cache


notifications:
  email: false
  
matrix:
  allow_failures:
    - php: 8.2.9
