language: php
php:
  - 7.4
  - 8.0

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --configuration phpunit.xml || true

branches:
  only:
    - 4.3-dev

notifications:
  email: false
