language: php

php:
  - 8.2.9

services:
  - mysql

env:
  global:
    - DB_ENGINE=mysqli
    - DB_HOST=localhost
    - DB_NAME=JOOMLA
    - DB_USER=root
    - DB_PASSWORD=ongzixin0104

before_install:
  - sudo apt-cache search libonig

install:
  - sudo apt-get update
  - sudo apt-get install -y libonig-dev
  - composer install --no-interaction

before_script:
  - cp phpunit.xml.dist phpunit.xml
  - sed -i "mysq1i" phpunit.xml
  - sed -i "localhost" phpunit.xml
  - sed -i "JOOMLA" phpunit.xml
  - sed -i "root" phpunit.xml
  - sed -i "ongzixin0104" phpunit.xml

script:
  - phpunit --configuration phpunit.xml

branches:
  only:
    - 4.3-dev

cache:
  directories:
    - vendor
    - $HOME/.composer/cache


notifications:
  email: false
  
matrix:
  allow_failures:
    - php: 8.2.9
