language: php								 .travis.yml
php:
  - 8.2.9
services:
  - mysql
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libonig-dev
  - mysql -e "USE mysql; UPDATE user SET authentication_string=PASSWORD('') WHERE User='root'; FLUSH PRIVILEGES;"
  - mysql -e 'CREATE DATABASE IF NOT EXISTS joomla;'
install:
  - composer self-update 2.5.8 --no-interaction
  - composer require phpunit/phpunit:^8.0 --dev --no-interaction
script:
  - phpunit --version
  - phpunit --configuration phpunit.xml
branches:
  all:
    - '*'
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
notifications:
  email: false

after_script:
  - bash generate_build_summary.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: artifacts
  on:
    branch: 4.3-dev  
    
matrix:
  allow_failures:
    - php: 8.2.9
