language: php

php:
  - 8.2.9

services:
  - mysql

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libonig-dev
  - mysql -e "USE mysql; UPDATE user SET authentication_string=PASSWORD('') WHERE User='root'; FLUSH PRIVILEGES;"
  - mysql -e 'CREATE DATABASE IF NOT EXISTS joomla;'

install:
  # Install specific Composer version (2.5.8)
  - composer self-update 2.5.8 --no-interaction

before_script:
  # Set up PHP and Composer globally
  - phpenv global 8.2.9
  - composer global require hirak/prestissimo

script:
  - phpunit --version
  - phpunit --configuration phpunit.xml

branches:
  only:
    - 4.3-dev

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

notifications:
  email: false

matrix:
  allow_failures:
    - php: 8.2.9
