language: php
php:
  - 8.2.9

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --configuration phpunit.xml

branches:
  only:
    - main

notifications:
  email: false

