name: CI

on:
  push:
    branches:
      - 4.3-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update system and install libonig-dev
      run: |
        sudo apt-get update
        sudo apt-get install -y libonig-dev
        mysql -e "USE mysql; UPDATE user SET authentication_string=PASSWORD('') WHERE User='root'; FLUSH PRIVILEGES;"
        mysql -e 'CREATE DATABASE IF NOT EXISTS joomla;
        
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Install dependencies
      run: composer install --no-interaction

    - name: Run tests
      run: libraries/vendor/bin/phpunit --configuration phpunit.xml
