name: CI

on:
  push:
    branches:
      - 4.3-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update system and install libonig-dev
      run: |
        sudo apt-get update
        sudo apt-get install -y libonig-dev

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Install dependencies
      run: composer install --no-interaction

    - name: Create MySQL Database
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      run: |
        mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS joomla;"



    - name: Run tests
      run: libraries/vendor/bin/phpunit --configuration phpunit.xml
