name: PHPUnit Tests

on:
  push:
    branches:
      - 4.3-dev

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: joomla
        ports:
          - 3308:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2.9
          coverage: none
          extensions: mbstring

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Set up MySQL database
        run: |
          sleep 10  # Wait for MySQL to be fully ready
          mysql -h 127.0.0.1 -P 3308 -u root -e "SET PASSWORD = 'ongzixin';"
          mysql -h 127.0.0.1 -P 3308 -u root -e "USE mysql; UPDATE user SET authentication_string=PASSWORD('') WHERE User='root'; FLUSH PRIVILEGES;"
          mysql -h 127.0.0.1 -P 3308 -u root -e 'CREATE DATABASE IF NOT EXISTS joomla;'

      - name: Modify PHPUnit configuration
        run: |
          echo "Updating PHPUnit configuration..."
          sed -i "s/'hostname' => 'localhost'/'hostname' => '127.0.0.1'/" phpunit.xml
          sed -i "s/'port' => 3306/'port' => 3308/" phpunit.xml
          sed -i "s/'username' => 'root'/'username' => 'root'/" phpunit.xml
          sed -i "s/'password' => ''/'password' => 'ongzixin'/" phpunit.xml

      - name: Run PHPUnit tests
        run: phpunit --version && phpunit --configuration phpunit.xml
